version: "3.1"
services:
  # NextJs Frontend
  frontend:
    container_name: Containers-Demo-FE
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000

  # MongoExpress
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-18-alpine3.18
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo-admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo-password
    ports:
      - 8081:8081

  # MongoDB
  mongodb:
    image: mongo:7.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo-password
    
